### ISSUE TITLE
Sort by time gives wrong results

### ISSUE THREAD

**Issue by jansol** [a-dekker/worldclock#3]
I noticed that for some reason Europe/Berlin comes after Europe/Helsinki (current). Maybe sorting gets confused by DST?

**Comment by a-dekker** [comment]
There was an issue with wrong ordering of local time. Ordering is based on UTC, not DST. Looks like it was cause by a different handling in Qt and QML./javascript. This should have been fixed in one of the latest versions (0.1-15), which is available in OpenRepos. I did test your case and the ordering looks okay.
I will upload a new version to the Harbour Store soon.
